app = "afripreneur-approved"
primary_region = "ams"
console_command = "/code/manage.py shell"
swap_size_mb = 2048


[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"

[[mounts]]
  source = "data"
  destination = "/data"
  initial_size = "1gb"
