# Generated by Django 5.1 on 2024-08-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("about", models.TextField()),
                ("date_founded", models.DateField()),
                ("location", models.CharField(max_length=100)),
                ("twitter", models.URLField()),
                ("website", models.URLField()),
                ("logo_url", models.URLField()),
            ],
            options={
                "verbose_name": "company",
                "verbose_name_plural": "companies",
            },
        ),
    ]
