# Generated by Django 5.1 on 2024-08-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="slug",
            field=models.SlugField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
