# Generated by Django 5.1 on 2024-08-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_company_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("company_website", models.URLField()),
                ("reason", models.TextField()),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "company request",
                "verbose_name_plural": "company requests",
            },
        ),
    ]
