# Generated by Django 5.1 on 2024-08-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_companyrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="about",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="date_founded",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="location",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="logo_url",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="twitter",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="website",
            field=models.URLField(null=True),
        ),
    ]
