# Generated by Django 5.1 on 2024-08-24 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0002_company_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyLegal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("terms_of_service", models.TextField()),
                ("date_effective", models.DateField(blank=True, null=True)),
                ("termination", models.TextField()),
                ("restrictions", models.TextField()),
                ("governing_law", models.TextField()),
                ("license_grants", models.TextField()),
                ("warranty", models.TextField()),
                ("liability", models.TextField()),
                ("disclaimer", models.TextField()),
                ("indemnification", models.TextField()),
                ("privacy_data_terms", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                    ),
                ),
            ],
        ),
    ]
