# Generated by Django 5.1 on 2024-08-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("legals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companylegal",
            name="disclaimer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companylegal",
            name="governing_law",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companylegal",
            name="indemnification",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companylegal",
            name="liability",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companylegal",
            name="license_grants",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companylegal",
            name="privacy_data_terms",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companylegal",
            name="restrictions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companylegal",
            name="termination",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companylegal",
            name="warranty",
            field=models.TextField(blank=True, null=True),
        ),
    ]
